### ISSUE TITLE
Много деклараций -export

### ISSUE THREAD

**Issue by bitgorbovsky** [nanshakov/erlangHW#2]
```erlang
-export([b_not/1]).
-export([b_and/2]).
-export([b_or/2]).
-export([b_xor/2]).
```

Совсем необязательно на каждую отдельную функцию писать отдельный экспорт. Иначе зачем тогда нужен списковый литерал в декларации экспорта?

Воспользуйтесь такой формой записи:
```erlang
-export([
    b_not/1,
    b_and/2,
    b_or/2,
    b_xor/2
]).
```

Но не стоит этим увлекаться. Иногда нужно все экспортируемые функции разбивать на группы экспортов, каждая группа представляется отдельной `-export` декларацией.

**Comment by nanshakov** [comment]
Понял, исправил в части модулей и далее буду делать так
